#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint
npm run prettier
npm run test

#!/bin/bash

# Protect master from accidental commits.
echo -e "===\n>> Pre-commit Hook: Checking branch name..."
branchName=$(git branch | grep '*' | sed 's/* //')

if [ $branchName == 'main' ]
then
 echo -e "\n🚫 Commit directly to main branch is not allowed!\n" && exit 1
fi

if [ $branchName == 'development' ]
then
  echo -e "\n🚫 Cannot push to remote development branch, please create your own branch and use PR.\n" && exit 1
fi

echo -e ">> Finish checking branch name.\n==="

exit 0